print("Pramod","Bansi","Chandan",sep="-",end='  ')
print("Pramod","Bansi","Chandan",sep="-",end='  ')
print("Pramod","Bansi","Chandan",sep="-",end='  ')
print("Pramod","Bansi","Chandan",sep="-",end='  ')
print("Pramod","Bansi","Chandan",sep="-",end='  ')
print("Pramod","Bansi","Chandan",sep="-",end='_')
print("Pramod","Bansi","Chandan",sep="-",end='_')
